### ISSUE TITLE
Unlocking other Amlogic devices.

### ISSUE THREAD

**Issue by MysteriousLog6** [npjohnson/sabrina-unlock#1]
Can this same exploit be used to unlock other Amlogic devices? Maybe the Mi Box 4k?

**Comment by npjohnson** [comment]
What SoC is the Mi Box 4k?

And what Android version is it's stock build?

**Comment by npjohnson** [comment]
But in short - not directly, but the concept can be adapted, yes.

You'd need to dump memory from burn-mode, isolate the AES key, use that to decrypt bootloader.img from your device, unpack it, pack BL2 to disable sig checks on BL33, and disable rollback checking. Then build a u-boot compatible with your device, and apply our u-boot commits atop it. Repack/encrypt it all, then run the exploit and boot it.

If the stock Android version is 9.0, it won't work because Amlogic secureboot forces checks on boot/dtb partitions even when bootloader unlocked.

**Comment by MysteriousLog6** [comment]
Sorry for late reply! 
It uses AmLogic S905L and uses Android 9.0.... It is supposedly firmware updated to Android 9 from 8.0
But doesn't the CCwGTV use a version above Android 9.0?

**Comment by MysteriousLog6** [comment]
You can downgrade it to Android 8 (The version it released with)

**Comment by npjohnson** [comment]
Yeah, sorry, you're out of luck, u-boots built for amlogic Android 9.0 require signed DTB/Boot images even when unlocked.

Even if we unlocked your device, it would be no hope. Same issue applies to 8.x firmwares as well.

**Comment by MysteriousLog6** [comment]
Big oof

**Comment by MysteriousLog6** [comment]
Big oof

**Comment by Stricted** [comment]
> Yeah, sorry, you're out of luck, u-boots built for amlogic Android 9.0 require signed DTB/Boot images even when unlocked.


> If the stock Android version is 9.0, it won't work because Amlogic secureboot forces checks on boot/dtb partitions even when bootloader unlocked.

i would not expect that any other amlogic device has the signature checks behind the config flag and i would expect even less that manufaturers set that flag

i assume this is google/askey specific

**Comment by MysteriousLog6** [comment]
So it possible?

**Comment by npjohnson** [comment]
Oh? Well that's good to hear. Would still need a bootable u-boot though - you could go poke Xiaomi about it.

They legally have legally have to release it.

**Comment by MysteriousLog6** [comment]
I have sent them a message , lets wait.
